name: gluu # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '4.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: gluu server
description: |
  Gluu server.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  gluu-sources:
    plugin: dump
    source: .
    override-pull: |
      mkdir -p opt/dist/gluu
      wget -nv https://ox.gluu.org/maven/org/gluu/oxshibbolethIdp/4.1.0.Final/oxshibbolethIdp-4.1.0.Final.war -O opt/dist/gluu/idp.war
      wget -nv https://ox.gluu.org/maven/org/gluu/oxtrust-server/4.1.0.Final/oxtrust-server-4.1.0.Final.war -O opt/dist/gluu/identity.war
      wget -nv https://ox.gluu.org/maven/org/gluu/oxauth-server/4.1.0.Final/oxauth-server-4.1.0.Final.war -O opt/dist/gluu/oxauth.war
      wget -nv https://ox.gluu.org/maven/org/gluu/oxauth-rp/4.1.0.Final/oxauth-rp-4.1.0.Final.war -O opt/dist/gluu/oxauth-rp.war
      wget -nv http://ox.gluu.org/maven/org/gluu/oxShibbolethStatic/4.1.0.Final/oxShibbolethStatic-4.1.0.Final.jar -O opt/dist/gluu/shibboleth-idp.jar
      wget -nv http://ox.gluu.org/maven/org/gluu/oxShibbolethKeyGenerator/4.1.0.Final/oxShibbolethKeyGenerator-4.1.0.Final.jar -O opt/dist/gluu/idp3_cml_keygenerator.jar
      mkdir -p opt/gluu/bin
      wget -nv https://raw.githubusercontent.com/GluuFederation/community-edition-setup/master/install.py -O opt/gluu/bin/install.py
      chmod +x opt/gluu/bin/install.py
      wget https://ox.gluu.org/npm/passport/passport-4.1.0.tgz -O opt/dist/gluu/passport.tgz
      wget https://ox.gluu.org/npm/passport/passport-version_4.1.0-node_modules.tar.gz -O opt/dist/gluu/passport-version_4.1.0-node_modules.tar.gz
      wget -nv https://ox.gluu.org/maven/org/gluu/super-gluu-radius-server/4.1.0.Final/super-gluu-radius-server-4.1.0.Final-distribution.zip -O opt/dist/gluu/gluu-radius-libs.zip
      wget -nv https://ox.gluu.org/maven/org/gluu/super-gluu-radius-server/4.1.0.Final/super-gluu-radius-server-4.1.0.Final.jar -O opt/dist/gluu/super-gluu-radius-server.jar
      wget https://ox.gluu.org/maven/org/gluu/casa/4.1.0.Final/casa-4.1.0.Final.war -O opt/dist/gluu/casa.war
      wget https://repo1.maven.org/maven2/com/twilio/sdk/twilio/7.17.0/twilio-7.17.0.jar -O opt/dist/gluu/twilio-7.17.0.jar
      wget https://search.maven.org/remotecontent?filepath=org/jsmpp/jsmpp/2.3.7/jsmpp-2.3.7.jar -O opt/dist/gluu/jsmpp-2.3.7.jar
      mkdir -p etc/certs
      wget https://github.com/GluuFederation/casa/raw/version_4.1.0/extras/casa.pub -O etc/certs/casa.pub
      mkdir -p oxd-server/bin 
      mkdir -p oxd-server/data 
      mkdir -p oxd-server/lib 
      mkdir -p oxd-server/conf
      wget https://raw.githubusercontent.com/GluuFederation/oxd/version_4.1.0/oxd-server/src/main/bin/lsox.sh -O oxd-server/bin/lsox.sh
      wget https://raw.githubusercontent.com/GluuFederation/oxd/version_4.1.0/oxd-server/src/main/bin/oxd-start.sh -O oxd-server/bin/oxd-start.sh
      wget https://raw.githubusercontent.com/GluuFederation/oxd/version_4.1.0/debian/oxd-server.sh -O oxd-server/bin/oxd-server.sh
      wget https://github.com/GluuFederation/oxd/raw/version_4.1.0/oxd-server/src/main/resources/oxd-server.keystore -O oxd-server/conf/oxd-server.keystore
      wget https://raw.githubusercontent.com/GluuFederation/oxd/version_4.1.0/oxd-server/src/main/resources/oxd-server.yml -O oxd-server/conf/oxd-server.yml
      wget https://raw.githubusercontent.com/GluuFederation/oxd/version_4.1.0/oxd-server/src/main/resources/swagger.yaml -O oxd-server/conf/swagger.yaml
      wget https://ox.gluu.org/maven/org/gluu/oxd-server/4.1.0.Final/oxd-server-4.1.0.Final.jar -O oxd-server/lib/oxd-server.jar
      wget https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.54/bcprov-jdk15on-1.54.jar -O oxd-server/lib/bcprov-jdk15on-1.54.jar
      tar -cvzf oxd-server.tgz oxd-server
      mv oxd-server.tgz opt/dist/gluu/.
      rm -rf oxd-server

    build-packages: 
      - wget
      - curl
      - tar

  amazon-corretto-jdk:
    plugin: dump
    source: https://d3pxv6yz143wms.cloudfront.net/8.222.10.1/amazon-corretto-8.222.10.1-linux-x64.tar.gz
    organize:
      "*" : opt/jre/
    stage-packages:
      - libgl1
      - libx11-6
      - libxdmcp6
      - libasound2
      - libatk1.0-0
      - libfontconfig1
      - libxcb1
      - libpng16-16
      - libxi6
      - libxrender1
      - libxtst6
    override-prime: |
     snapcraftctl prime
     cd $SNAPCRAFT_PRIME/opt/jre/jre/lib/security; mv cacerts cacerts.bak; ln -s /var/snap/gluu/common/etc/certs/java-cacerts

  jython:
    plugin: nil
    after: [amazon-corretto-jdk]
    override-prime: |
     wget https://repo1.maven.org/maven2/org/python/jython-installer/2.7.2rc1/jython-installer-2.7.2rc1.jar -O $SNAPCRAFT_PRIME/jython-installer.jar
     $SNAPCRAFT_PRIME/opt/jre/bin/java -jar $SNAPCRAFT_PRIME/jython-installer.jar -v -s -d $SNAPCRAFT_PRIME/opt/jython -t standard -e ensurepip
     rm $SNAPCRAFT_PRIME/jython-installer.jar
  
  jetty:
    plugin: dump
    source: https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.19.v20190610/jetty-distribution-9.4.19.v20190610.tar.gz
    organize:
     "*" : opt/jetty/
    override-prime: |
      snapcraftctl prime
