name: gluu-server
base: core18
version: '4.1'
summary: gluu server community edition.
description: |
  Gluu Server Community Edition.
  Central authentication and authorization for web & mobile applications.

grade: devel 
confinement: devmode

parts:
  
  depends:
    plugin: nil
    stage-packages:
     - apache2
     - python
     - python-ldap
     - python-ldap3
     - python-requests
     - zip

  gluu-sources:
    plugin: dump
    source: .
    override-pull: |
      mkdir -p opt/dist/gluu
      wget -nv https://ox.gluu.org/maven/org/gluu/oxshibbolethIdp/4.1.0.Final/oxshibbolethIdp-4.1.0.Final.war -O opt/dist/gluu/idp.war
      wget -nv https://ox.gluu.org/maven/org/gluu/oxtrust-server/4.1.0.Final/oxtrust-server-4.1.0.Final.war -O opt/dist/gluu/identity.war
      wget -nv https://ox.gluu.org/maven/org/gluu/oxauth-server/4.1.0.Final/oxauth-server-4.1.0.Final.war -O opt/dist/gluu/oxauth.war
      wget -nv https://ox.gluu.org/maven/org/gluu/oxauth-rp/4.1.0.Final/oxauth-rp-4.1.0.Final.war -O opt/dist/gluu/oxauth-rp.war
      wget -nv http://ox.gluu.org/maven/org/gluu/oxShibbolethStatic/4.1.0.Final/oxShibbolethStatic-4.1.0.Final.jar -O opt/dist/gluu/shibboleth-idp.jar
      wget -nv http://ox.gluu.org/maven/org/gluu/oxShibbolethKeyGenerator/4.1.0.Final/oxShibbolethKeyGenerator-4.1.0.Final.jar -O opt/dist/gluu/idp3_cml_keygenerator.jar
    build-packages: 
      - wget
      
  setup-py:
    plugin: dump
    source: https://github.com/GluuFederation/community-edition-setup/archive/version_4.1.0.zip
    source-type: zip
    organize: 
      "*" : install/community-edition-setup/
    build-packages:
      - zip

  install-py:
    plugin: dump
    source: .
    override-pull: |
      mkdir -p opt/gluu/bin
      wget -nv https://raw.githubusercontent.com/GluuFederation/community-edition-setup/master/install.py -O opt/gluu/bin/install.py
      chmod +x opt/gluu/bin/install.py
    build-packages: 
      - wget
     
  casa-files:
    plugin: dump
    source: .
    override-pull: |
      mkdir -p opt/dist/gluu
      mkdir -p etc/certs
      wget -nv https://github.com/GluuFederation/casa/raw/version_4.1.0/extras/casa.pub -O etc/certs/casa.pub
      wget -nv https://ox.gluu.org/maven/org/gluu/super-gluu-radius-server/4.1.0.Final/super-gluu-radius-server-4.1.0.Final.jar -O opt/dist/gluu/super-gluu-radius-server.jar
      wget -nv https://ox.gluu.org/maven/org/gluu/casa/4.1.0.Final/casa-4.1.0.Final.war -O opt/dist/gluu/casa.war
      wget -nv https://repo1.maven.org/maven2/com/twilio/sdk/twilio/7.17.0/twilio-7.17.0.jar -O opt/dist/gluu/twilio-7.17.0.jar
      wget -nv https://search.maven.org/remotecontent?filepath=org/jsmpp/jsmpp/2.3.7/jsmpp-2.3.7.jar -O opt/dist/gluu/jsmpp-2.3.7.jar
    build-packages: 
      - wget      
  
  super-radius:
    plugin: dump
    source: https://ox.gluu.org/maven/org/gluu/super-gluu-radius-server/4.1.0.Final/super-gluu-radius-server-4.1.0.Final-distribution.zip 
    organize:
      "*" : opt/dist/gluu/gluu-radius-libs/
  
  oxd-files:
    plugin: dump
    source: .
    override-pull: |
      mkdir -p oxd-server/bin 
      mkdir -p oxd-server/data 
      mkdir -p oxd-server/lib 
      mkdir -p oxd-server/conf
      wget https://raw.githubusercontent.com/GluuFederation/oxd/version_4.1.0/oxd-server/src/main/bin/lsox.sh -O oxd-server/bin/lsox.sh
      wget https://raw.githubusercontent.com/GluuFederation/oxd/version_4.1.0/oxd-server/src/main/bin/oxd-start.sh -O oxd-server/bin/oxd-start.sh
      wget https://raw.githubusercontent.com/GluuFederation/oxd/version_4.1.0/debian/oxd-server.sh -O oxd-server/bin/oxd-server.sh
      wget https://github.com/GluuFederation/oxd/raw/version_4.1.0/oxd-server/src/main/resources/oxd-server.keystore -O oxd-server/conf/oxd-server.keystore
      wget https://raw.githubusercontent.com/GluuFederation/oxd/version_4.1.0/oxd-server/src/main/resources/oxd-server.yml -O oxd-server/conf/oxd-server.yml
      wget https://raw.githubusercontent.com/GluuFederation/oxd/version_4.1.0/oxd-server/src/main/resources/swagger.yaml -O oxd-server/conf/swagger.yaml
      wget https://ox.gluu.org/maven/org/gluu/oxd-server/4.1.0.Final/oxd-server-4.1.0.Final.jar -O oxd-server/lib/oxd-server.jar
      wget https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.54/bcprov-jdk15on-1.54.jar -O oxd-server/lib/bcprov-jdk15on-1.54.jar
      tar -cvzf oxd-server.tgz oxd-server
      mkdir -p opt/dist/gluu
      mv oxd-server.tgz opt/dist/gluu/.
      rm -rf oxd-server
    build-packages: 
      - wget
      - tar

  passport:
    plugin: dump
    source: https://ox.gluu.org/npm/passport/passport-4.1.0.tgz 
    source-type: tar
    organize:
      "*" : opt/dist/gluu/passport/

  passport-node:
    plugin: dump
    source: https://ox.gluu.org/npm/passport/passport-version_4.1.0-node_modules.tar.gz
    source-type: tar
    organize:
      "*" : opt/dist/gluu/passport-node/

  corretto:
    plugin: dump
    source: https://d3pxv6yz143wms.cloudfront.net/8.222.10.1/amazon-corretto-8.222.10.1-linux-x64.tar.gz
    organize:
      "*" : opt/jre/
    stage-packages:
      - libgl1
      - libx11-6
      - libxdmcp6
      - libasound2
      - libatk1.0-0
      - libfontconfig1
      - libxcb1
      - libpng16-16
      - libxi6
      - libxrender1
      - libxtst6
    override-prime: |
     snapcraftctl prime
     cd $SNAPCRAFT_PRIME/opt/jre/jre/lib/security; mv cacerts cacerts.bak; ln -s /var/snap/gluu/common/etc/certs/java-cacerts

  jython:
    plugin: dump
    source: .
    override-pull: |
     mkdir -p opt/dist/app/
     wget https://repo.gluu.org/snap-deps/jython-installer-2.7.2a.jar -O opt/dist/app/jython-installer.jar
    build-packages:
      - wget

  jetty:
    plugin: dump
    source: https://repo.gluu.org/snap-deps/jetty-distribution-9.4.26.v20200117.tar.gz
    organize:
     "*" : opt/jetty/
    override-prime: |
      snapcraftctl prime
      mkdir -p $SNAPCRAFT_PRIME/opt/dist/scripts/
      cp $SNAPCRAFT_PRIME/opt/jetty/bin/jetty.sh $SNAPCRAFT_PRIME/opt/dist/scripts/oxauth 
      cp $SNAPCRAFT_PRIME/opt/jetty/bin/jetty.sh $SNAPCRAFT_PRIME/opt/dist/scripts/identity 
      chmod +x $SNAPCRAFT_PRIME/opt/dist/scripts/oxauth
      chmod +x $SNAPCRAFT_PRIME/opt/dist/scripts/identity

  node:
    plugin: dump
    source: https://nodejs.org/dist/v12.16.0/node-v12.16.0-linux-x64.tar.xz
    organize:
     "*" : opt/node/

  opendj:
    plugin: dump
    source: https://ox.gluu.org/maven/org/forgerock/opendj/opendj-server-legacy/4.0.0-M3/opendj-server-legacy-4.0.0-M3.zip
    organize:  
      "*" : opt/

apps:
  gluu-setup:
    command: 
      python install/community-edition-setup/setup.py

  gluu-start:
    command:
      opt/opendj/bin/start-ds
      opt/dist/scripts/oxauth start
      opt/dist/scripts/identity start
    daemon: simple
    plugs:
      - network
      - network-bind

  gluu-stop:
    command: 
      opt/opendj/bin/stop-ds
      opt/dist/scripts/identity stop
      opt/dist/scripts/oxauth stop
    daemon: simple
    plugs:
     - network
     - network-bind
