name: gluu-server
version: 1
summary: Central authentication and authorization for web and mobile applications.
description: |
  Identity & access management (IAM) platform for web & mobile single sign-on (SSO), 
  two-factor authentication (2FA) and API access management.

confinement: strict
base: core18

passthrough:

  layout:
    /opt/jre:
      symlink: $SNAP/gluu-opt/jre
    /opt/jetty:
      symlink: $SNAP/gluu-opt/jetty
    /etc/gluu:
       bind: $SNAP_COMMON/etc/gluu
    #/var/run/jetty:
    #    type: tmpfs
    /etc/certs:
       symlink: $SNAP_COMMON/etc/certs
    /etc/default/oxauth:
       symlink: $SNAP_COMMON/etc/default/oxauth
    /opt/gluu/jetty/oxauth:
      symlink: $SNAP_COMMON/gluu/jetty/oxauth

  system-usernames:
    snap_daemon: shared

parts:

  amazon-corretto-jdk:
     plugin: dump
     source: https://d3pxv6yz143wms.cloudfront.net/8.222.10.1/amazon-corretto-8.222.10.1-linux-x64.tar.gz
     organize:
      "*" : gluu-opt/jre/
     stage-packages:
       # the following packages are needed for amazon-corretto-jdk
       - libgl1
       - libx11-6
       - libxdmcp6
       - libasound2
       - libatk1.0-0
       - libfontconfig1
       - libxcb1
       - libpng16-16
       - libxi6
       - libxrender1
       - libxtst6

     override-prime: |
       snapcraftctl prime
       cd $SNAPCRAFT_PRIME/gluu-opt/jre/jre/lib/security; mv cacerts cacerts.bak; ln -s /var/snap/gluu-server/common/etc/certs/java-cacerts

  jetty:
    plugin: dump
    source: https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.19.v20190610/jetty-distribution-9.4.19.v20190610.tar.gz
    organize:
      "*" : gluu-opt/jetty/
    override-prime: |
      snapcraftctl prime


  jython:
    plugin: nil
    after: [amazon-corretto-jdk]
    override-prime: |
      snapcraftctl prime
      if [ ! -d "$SNAPCRAFT_PRIME/gluu-opt/jython" ]; then
        wget https://repo1.maven.org/maven2/org/python/jython-installer/2.7.2rc1/jython-installer-2.7.2rc1.jar -O $SNAPCRAFT_PRIME/jython-installer.jar
        $SNAPCRAFT_PRIME/gluu-opt/jre/bin/java -jar $SNAPCRAFT_PRIME/jython-installer.jar -v -s -d $SNAPCRAFT_PRIME/gluu-opt/jython -t standard -e ensurepip
        rm $SNAPCRAFT_PRIME/jython-installer.jar
      fi

  oxauth:
    plugin: nil
    override-prime: |
      snapcraftctl prime
      mkdir -p $SNAPCRAFT_PRIME/gluu-opt/dist/gluu
      mkdir -p $SNAPCRAFT_PRIME/gluu-opt/dist/scripts
      cp /home/adrian/temp/oxauth $SNAPCRAFT_PRIME/gluu-opt/dist/scripts
      wget https://ox.gluu.org/maven/org/gluu/oxauth-server/4.1.0.Final/oxauth-server-4.1.0.Final.war -O $SNAPCRAFT_PRIME/gluu-opt/dist/gluu/oxauth-server.war
    stage-packages:
      - dpkg
      - coreutils
      - login


apps:

  jython:
    environment:
      JAVA_HOME: "/opt/jre"
    command: gluu-opt/jre/bin/java  -jar $SNAP/gluu-opt/jython/jython.jar

  oxauth:
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA: "/opt/jre/bin/java"
      JETTY_HOME: "/opt/jetty"
      JETTY_RUN: "/tmp"
      JETTY_USER: "root"
      JETTY_SHELL: "/bin/sh"

    plugs:
     - network
     - network-bind

    daemon: forking
    command: gluu-opt/dist/scripts/oxauth start

    #stop-command: gluu-opt/dist/scripts/oxauth stop

