name: gluu-server
version: 1
summary: Central authentication and authorization for web and mobile applications.
description: |
  Identity & access management (IAM) platform for web & mobile single sign-on (SSO), 
  two-factor authentication (2FA) and API access management.

confinement: strict
base: core18

passthrough:
  system-usernames:
    snap_daemon: shared

  layout:
    /opt/gluu:
      bind: $SNAP/opt/gluu
    #/opt/gluu/jetty/oxauth/oxauth.state:
    #  bind-file: $SNAP_COMMON/gluu/jetty/oxauth/oxauth.state

parts:

  amazon-corretto-jdk:
     plugin: dump
     source: https://d3pxv6yz143wms.cloudfront.net/8.222.10.1/amazon-corretto-8.222.10.1-linux-x64.tar.gz
     organize:
      "*" : opt/amazon-corretto-8.222.10.1-linux-x64/
     stage-packages:
       # the following packages are needed for amazon-corretto-jdk
       - libgl1
       - libx11-6
       - libxdmcp6
       - libasound2
       - libatk1.0-0
       - libfontconfig1
       - libxcb1
       - libpng16-16
       - libxi6
       - libxrender1
       - libxtst6
     override-prime: |
       snapcraftctl prime
        ln -s $SNAPCRAFT_PRIME/opt/amazon-corretto-8.222.10.1-linux-x64 $SNAPCRAFT_PRIME/opt/jre

  jetty:
    plugin: dump
    source: https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.19.v20190610/jetty-distribution-9.4.19.v20190610.tar.gz
    organize:
      "*" : opt/jetty-9.4/
    override-prime: |
       snapcraftctl prime
        ln -s $SNAPCRAFT_PRIME/opt/jetty-9.4 $SNAPCRAFT_PRIME/opt/jetty


  opendj:
    plugin: dump
    source: https://ox.gluu.org/maven/org/forgerock/opendj/opendj-server-legacy/4.0.0-M3/opendj-server-legacy-4.0.0-M3.zip
    source-type: zip
    organize:
      '*' : opt/
    stage-packages:
       - libpam-cap
       - libcap2-bin
    override-prime: |
      snapcraftctl prime
      echo "/var/snap/gluu-server/common/opendj" > $SNAPCRAFT_PRIME/opt/opendj/instance.loc

  jython:
    plugin: nil
    after: [amazon-corretto-jdk]
    override-prime: |
      snapcraftctl prime
      wget https://repo1.maven.org/maven2/org/python/jython-installer/2.7.2rc1/jython-installer-2.7.2rc1.jar -O jython-installer.jar
      $SNAPCRAFT_PRIME/opt/jre/bin/java -jar jython-installer.jar -v -s -d $SNAPCRAFT_PRIME/opt/jython-2.7.2rc1 -t standard -e ensurepip
      ln -s $SNAPCRAFT_PRIME/opt/jython-2.7.2rc1 $SNAPCRAFT_PRIME/opt/jython
      rm jython-installer.jar

  oxauth:
    plugin: nil
    override-prime: |
      snapcraftctl prime
      wget https://ox.gluu.org/maven/org/gluu/oxauth-server/4.1.0.Final/oxauth-server-4.1.0.Final.war -O oxauth.war
      mkdir -p $SNAPCRAFT_PRIME/opt/gluu/jetty/oxauth/webapps
      cp oxauth.war $SNAPCRAFT_PRIME/opt/gluu/jetty/oxauth/webapps

apps:

  opendj-setup:
    plugs:
     - network
     - network-bind
    environment:
      JAVA_HOME: "$SNAP/opt/jre"
      JAVA_BIN: "$SNAP/opt/jre/bin/java"
      OPENDJ_JAVA_HOME: "$SNAP/opt/jre"
    command: opt/opendj/setup

  opendj-start:
    plugs:
     - network
     - network-bind
    environment:
      JAVA_HOME: "$SNAP/opt/jre"
      JAVA_BIN: "$SNAP/opt/jre/bin/java"
      OPENDJ_JAVA_HOME: "$SNAP/opt/jre"
    command: opt/opendj/bin/start-ds

  opendj-stop:
    environment:
      JAVA_HOME: "$SNAP/opt/jre"
      JAVA_BIN: "$SNAP/opt/jre/bin/java"
      OPENDJ_JAVA_HOME: "$SNAP/opt/jre"
    command: opt/opendj/bin/stop-ds

  opendj:
    environment:
      JAVA_HOME: "$SNAP/opt/jre"
      JAVA_BIN: "$SNAP/opt/jre/bin/java"
      OPENDJ_JAVA_HOME: "$SNAP/opt/jre"
    plugs:
     - network
     - network-bind
    daemon: forking
    command: opt/opendj/bin/start-ds
    stop-command: opt/opendj/bin/stop-ds


  jython:
    environment:
      JAVA_HOME: "$SNAP/opt/jre"
      JAVA_BIN: "$SNAP/opt/jre/bin/java"
    command: opt/jre/bin/java  -jar $SNAP/opt/jython/jython.jar
