name: gluu-server
version: '4.1"
summary: Central authentication and authorization for web and mobile applications.
description: |
  Identity & access management (IAM) platform for web & mobile single sign-on (SSO), 
  two-factor authentication (2FA) and API access management.

grade: stable
confinement: strict
base: core18

passthrough:

  layout:
    /opt/jre:
      symlink: $SNAP/gluu-opt/jre
    /opt/jetty:
      symlink: $SNAP/gluu-opt/jetty
    /opt/opendj:
      symlink: $SNAP/gluu-opt/opendj
    /opt/node:
      symlink: $SNAP/gluu-opt/node
    /opt/oxd-server:
      symlink: $SNAP/gluu-opt/oxd-server
    /etc/gluu:
       bind: $SNAP_COMMON/etc/gluu
    /opt/install:
      symlink: $SNAP_COMMON/install
    /var/gluu:
        symlink: $SNAP_COMMON/var/gluu
    /etc/certs:
       symlink: $SNAP_COMMON/etc/certs

    /etc/default:
      bind: $SNAP_COMMON/etc/default

    /opt/gluu:
      symlink: $SNAP_COMMON/gluu
    /opt/dist:
      symlink: $SNAP/gluu-opt/dist
    /usr/lib/apache2:
      symlink: $SNAP/usr/lib/apache2
    /usr/share/apache2:
      symlink: $SNAP/usr/share/apache2
    /var/www/html:
      symlink: $SNAP_COMMON/var/www/html
    /etc/ssl/openssl.cnf:
      bind-file: $SNAP/etc/ssl/openssl.cnf
    /opt/shibboleth-idp:
      symlink: $SNAP_COMMON/gluu/shibboleth-idp
    /usr/bin/facter:
      symlink: $SNAP/usr/bin/facter

parts:

  base-system:
    plugin: nil
    stage-packages:
      - bash
      - sed
      - openssl
      #followings are for opendj
      - libpam-cap
      - libcap2-bin
      #followings are for oxauth
      - dpkg
      - coreutils
      - login

    override-prime: |
      snapcraftctl prime
      sed 's/^RANDFILE/#&/' -i $SNAPCRAFT_PRIME/etc/ssl/openssl.cnf

  python:
    after: [base-system]
    plugin: python
    stage-packages:
      - python3
      - python3-pip
      - python3-ldap
      - python3-ldap3
      - python3-requests
    python-packages:
     - pyyaml
     - psutil
     
  yacron:
   after: [base-system]
   plugin: python
   python-packages:
     - yacron


  facter:
    plugin: dump
    source: facter
    source-type: local
    organize:
      "*" : /usr/bin/

  apache2:
    after: [base-system]
    plugin: nil
    stage-packages:
      - apache2

  setup-starter:
    plugin: dump
    source: setup/starter
    source-type: local
    organize:
      "*" : bin/

  community-edition-setup:
    plugin: dump
    source: apps/setup/
    source-type: local
    organize:
      "*" : /gluu-opt/dist/gluu/

  amazon-corretto-jdk:
    after: [base-system]
    plugin: dump
    source: apps/corretto/amazon-corretto.tar.gz
    organize:
      "*" : gluu-opt/jre/
    stage-packages:
      # the following packages are needed for amazon-corretto-jdk
      - libgl1
      - libx11-6
      - libxdmcp6
      - libasound2
      - libatk1.0-0
      - libfontconfig1
      - libxcb1
      - libpng16-16
      - libxi6
      - libxrender1
      - libxtst6
      - libcairo2
      - libgdk-pixbuf2.0-0
      - libgraphite2-3
      - libharfbuzz0b
      - libpango-1.0-0 
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libthai0
      - libxcb-render0
      - libxcb-shm0

    override-prime: |
      snapcraftctl prime
      if [ -f "$SNAPCRAFT_PRIME/gluu-opt/jre/jre/lib/security/cacerts" ]; then
        mv $SNAPCRAFT_PRIME/gluu-opt/jre/jre/lib/security/cacerts $SNAPCRAFT_PRIME/gluu-opt/jre/jre/lib/security/cacerts.bak
        ln -s /var/snap/gluu-server/common/etc/certs/java-cacerts $SNAPCRAFT_PRIME/gluu-opt/jre/jre/lib/security/cacerts
      fi


  jetty:
    plugin: dump
    source: apps/jetty/jetty.tar.gz
    organize:
      "*" : gluu-opt/jetty/

  jython:
    plugin: dump
    after: [amazon-corretto-jdk]
    source: apps/jython/
    organize:
      "*" : /gluu-opt/dist/gluu/
    source-type: local
    override-prime: |
      snapcraftctl prime
      if [ ! -d "$SNAPCRAFT_PRIME/gluu-opt/jython" ]; then
        $SNAPCRAFT_PRIME/gluu-opt/jre/bin/java -jar $SNAPCRAFT_PRIME/gluu-opt/dist/gluu/jython-installer.jar -v -s -d $SNAPCRAFT_PRIME/gluu-opt/jython -t standard -e ensurepip
        rm $SNAPCRAFT_PRIME/gluu-opt/dist/gluu/jython-installer.jar
      fi

  node:
    plugin: dump
    source: apps/node/node.tar.xz
    organize:
      "*" : gluu-opt/node

  opendj:
    after: [jython]
    plugin: dump
    source: apps/opendj/opendj-server.zip
    source-type: zip
    organize:
      '*' : gluu-opt/
    override-prime: |
      snapcraftctl prime
      echo "/var/snap/$SNAPCRAFT_PROJECT_NAME/common/opendj" > $SNAPCRAFT_PRIME/gluu-opt/opendj/instance.loc

  oxauth:
    after: [jetty]
    plugin: dump
    source: apps/oxauth
    source-type: local
    organize:
      "*" : /gluu-opt/dist/gluu/
    override-prime: |
      snapcraftctl prime
      mkdir -p $SNAPCRAFT_PRIME/gluu-opt/dist/scripts
      cp $SNAPCRAFT_PRIME/gluu-opt/jetty/bin/jetty.sh $SNAPCRAFT_PRIME/gluu-opt/dist/scripts/oxauth

  identity:
    plugin: dump
    after: [oxauth]
    source: apps/identity
    organize:
      "*" : /gluu-opt/dist/gluu/
    override-prime: |
      snapcraftctl prime
      cp $SNAPCRAFT_PRIME/gluu-opt/jetty/bin/jetty.sh $SNAPCRAFT_PRIME/gluu-opt/dist/scripts/identity

  oxauth-rp:
    plugin: nil
    after: [identity]
    override-prime: |
      snapcraftctl prime
      cp $SNAPCRAFT_PRIME/gluu-opt/jetty/bin/jetty.sh $SNAPCRAFT_PRIME/gluu-opt/dist/scripts/oxauth-rp

  idp:
    plugin: dump
    after: [identity]
    source: apps/idp
    organize:
      "*" : /gluu-opt/dist/gluu/
    override-prime: |
      snapcraftctl prime
      cp $SNAPCRAFT_PRIME/gluu-opt/jetty/bin/jetty.sh $SNAPCRAFT_PRIME/gluu-opt/dist/scripts/idp

  casa:
    plugin: dump
    after: [identity]
    source: apps/casa
    organize:
      "*" : /gluu-opt/dist/gluu/
    override-prime: |
      snapcraftctl prime
      cp $SNAPCRAFT_PRIME/gluu-opt/jetty/bin/jetty.sh $SNAPCRAFT_PRIME/gluu-opt/dist/scripts/casa

  oxd-server:
    plugin: dump
    source: apps/oxd-server/oxd-server.zip
    organize:
      "*" : /gluu-opt/oxd-server

  oxd-server-start:
    plugin: dump
    source: apps/oxd-server/start
    source-type: local
    organize:
      "*" : gluu-opt/dist/scripts/
    override-prime: |
      snapcraftctl prime
      chmod +x $SNAPCRAFT_PRIME/gluu-opt/dist/scripts/oxd-server


  passport:
    plugin: dump
    source: apps/passport
    organize:
      "*" : /gluu-opt/dist/gluu/
    override-prime: |
      snapcraftctl prime
      mv $SNAPCRAFT_PRIME/gluu-opt/dist/gluu/passport $SNAPCRAFT_PRIME/gluu-opt/dist/scripts/passport
      chmod +x $SNAPCRAFT_PRIME/gluu-opt/dist/scripts/passport


  gluu-radius:
    plugin: dump
    source: apps/radius
    organize:
      "*" : /gluu-opt/dist/gluu/
    override-prime: |
      snapcraftctl prime
      if [ ! -d "$SNAPCRAFT_PRIME/gluu-opt/dist/scripts" ]; then
        mkdir -p $SNAPCRAFT_PRIME/gluu-opt/dist/scripts
      fi
      mv $SNAPCRAFT_PRIME/gluu-opt/dist/gluu/gluu-radius $SNAPCRAFT_PRIME/gluu-opt/dist/scripts/gluu-radius
      chmod +x $SNAPCRAFT_PRIME/gluu-opt/dist/scripts/gluu-radius


apps:

  bash:
    plugs:
     - network
     - network-bind
     - network-observe
     - block-devices
     - mount-observe
     - system-observe
     
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA_BIN: "/opt/jre/bin/java"
      OPENDJ_JAVA_HOME: "/opt/jre"
      PYTHONWARNINGS: "ignore"
    command: bin/bash

  yacron:
    command: bin/yacron -c $SNAP_COMMON/etc/cron-jobs.yaml
    daemon: simple

  python:
    plugs:
     - network
     - network-bind
    command: usr/bin/python3

  setup:
    plugs:
     - network
     - network-bind
    command: usr/bin/python3 $SNAP/bin/setup.py

  apache:
    environment:
      APACHE_RUN_USER:  "daemon"
      APACHE_RUN_GROUP: "daemon"
      APACHE_PID_FILE:  "/opt/gluu/run/apache2/apache2.pid"
      APACHE_RUN_DIR:   "/opt/gluu/run/apache2"
      APACHE_LOCK_DIR:  "/opt/gluu/run/apache2"
      APACHE_LOG_DIR:   "/opt/gluu/log/apache2"

    command: usr/sbin/apache2 -d $SNAP_COMMON/etc/apache2 -k start
    stop-command: usr/sbin/apache2 -d $SNAP_COMMON/etc/apache2 -k stop
    daemon: forking
    restart-condition: always
    plugs:
      - network
      - network-bind

  jython:
    environment:
      JAVA_HOME: "/opt/jre"
    command: gluu-opt/jre/bin/java  -jar $SNAP/gluu-opt/jython/jython.jar


  opendj-setup:
    plugs:
     - network
     - network-bind
     - mount-observe
     
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA_BIN: "/opt/jre/bin/java"
      OPENDJ_JAVA_HOME: "/opt/jre"
    command: gluu-opt/opendj/setup


  opendj:
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA_BIN: "/opt/jre/bin/java"
      OPENDJ_JAVA_HOME: "/opt/jre"
    plugs:
     - network
     - network-bind
    daemon: forking
    command: gluu-opt/opendj/bin/start-ds
    stop-command: gluu-opt/opendj/bin/stop-ds


  oxauth:
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA: "/opt/jre/bin/java"

    plugs:
     - network
     - network-bind

    daemon: forking
    command: gluu-opt/dist/scripts/oxauth start
    stop-command: gluu-opt/dist/scripts/oxauth stop


  identity:
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA: "/opt/jre/bin/java"
      PYTHONWARNINGS: "ignore"

    plugs:
     - network
     - network-bind
     - network-observe
     - block-devices
     - mount-observe
     - system-observe

    daemon: forking
    command: gluu-opt/dist/scripts/identity start
    stop-command: gluu-opt/dist/scripts/identity stop

  idp:
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA: "/opt/jre/bin/java"

    plugs:
     - network
     - network-bind

    daemon: forking
    command: gluu-opt/dist/scripts/idp start
    stop-command: gluu-opt/dist/scripts/idp stop

  oxauth-rp:
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA: "/opt/jre/bin/java"

    plugs:
     - network
     - network-bind

    daemon: forking
    command: gluu-opt/dist/scripts/oxauth-rp start
    stop-command: gluu-opt/dist/scripts/oxauth-rp stop

  casa:
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA: "/opt/jre/bin/java"

    plugs:
     - network
     - network-bind

    daemon: forking
    command: gluu-opt/dist/scripts/casa start
    stop-command: gluu-opt/dist/scripts/casa stop

  passport:
    plugs:
     - network
     - network-bind

    daemon: forking
    command: gluu-opt/dist/scripts/passport start
    stop-command: gluu-opt/dist/scripts/passport stop

  gluu-radius:
    plugs:
     - network
     - network-bind

    daemon: forking
    command: gluu-opt/dist/scripts/gluu-radius start
    stop-command: gluu-opt/dist/scripts/gluu-radius stop


  oxd-server:
    plugs:
     - network
     - network-bind

    daemon: forking
    command: gluu-opt/dist/scripts/oxd-server start
    stop-command: gluu-opt/dist/scripts/oxd-server stop
    


