name: gluu-server
version: 1
summary: Central authentication and authorization for web and mobile applications.
description: |
  Identity & access management (IAM) platform for web & mobile single sign-on (SSO), 
  two-factor authentication (2FA) and API access management.

confinement: strict
base: core18

passthrough:

  system-usernames:
    snap_daemon: shared

  layout:
    /opt/jre:
      symlink: $SNAP/gluu-opt/jre
    /opt/jetty:
      symlink: $SNAP/gluu-opt/jetty
    /opt/opendj:
      symlink: $SNAP/gluu-opt/opendj
    /etc/gluu:
       bind: $SNAP_COMMON/etc/gluu
    /opt/install:
      symlink: $SNAP_COMMON/install
    /var/gluu:
        symlink: $SNAP_COMMON/var/gluu
    /etc/certs:
       symlink: $SNAP_COMMON/etc/certs
    /etc/default/oxauth:
       symlink: $SNAP_COMMON/etc/default/oxauth
    /etc/default/identity:
       symlink: $SNAP_COMMON/etc/default/identity
    /opt/gluu:
      symlink: $SNAP_COMMON/gluu
    /opt/dist:
      symlink: $SNAP/gluu-opt/dist
    /usr/lib/apache2:
        symlink: $SNAP/usr/lib/apache2
    /usr/share/apache2:
        symlink: $SNAP/usr/share/apache2

    
parts:

  base-system:
   plugin: nil
   stage-packages:
     - bash
     - python3
     - python3-ldap
     - python3-ldap3
     - python3-requests
     
     - openssl

  apache2:
    plugin: nil
    stage-packages:
      - apache2
    override-prime: |
      snapcraftctl prime
      cp $SNAPCRAFT_PRIME/../setup/envvars.apache2 $SNAPCRAFT_PRIME/etc/apache2/envvars
    
  setup-starter:
    plugin: dump
    source: setup/starter
    organize:
      "*" : bin/

  packages:
    plugin: nil
    override-prime: |
      cp $SNAPCRAFT_PRIME/../apps/community-edition-setup.zip $SNAPCRAFT_PRIME/gluu-opt/dist/gluu/community-edition-setup.zip
      cp $SNAPCRAFT_PRIME/../apps/oxauth-client-jar-with-dependencies.jar $SNAPCRAFT_PRIME/gluu-opt/dist/gluu/oxauth-client-jar-with-dependencies.jar

  amazon-corretto-jdk:
    plugin: dump
    source: apps/amazon-corretto.tar.gz
    organize:
      "*" : gluu-opt/jre/
    stage-packages:
      # the following packages are needed for amazon-corretto-jdk
      - libgl1
      - libx11-6
      - libxdmcp6
      - libasound2
      - libatk1.0-0
      - libfontconfig1
      - libxcb1
      - libpng16-16
      - libxi6
      - libxrender1
      - libxtst6
      - libcairo2
      - libgdk-pixbuf2.0-0
      - libgraphite2-3
      - libharfbuzz0b
      - libpango-1.0-0 
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libthai0
      - libxcb-render0
      - libxcb-shm0

    override-prime: |
      snapcraftctl prime
      if [ -f "$SNAPCRAFT_PRIME/gluu-opt/jre/jre/lib/security/cacerts" ]; then
        mv $SNAPCRAFT_PRIME/gluu-opt/jre/jre/lib/security/cacerts $SNAPCRAFT_PRIME/gluu-opt/jre/jre/lib/security/cacerts.bak
        ln -s /var/snap/gluu-server/common/etc/certs/java-cacerts $SNAPCRAFT_PRIME/gluu-opt/jre/jre/lib/security/cacerts
      fi


  jetty:
    plugin: dump
    source: apps/jetty.tar.gz
    organize:
      "*" : gluu-opt/jetty/
    override-prime: |
      snapcraftctl prime


  jython:
    plugin: nil
    after: [amazon-corretto-jdk]
    override-prime: |
      snapcraftctl prime
      if [ ! -d "$SNAPCRAFT_PRIME/gluu-opt/jython" ]; then
        $SNAPCRAFT_PRIME/gluu-opt/jre/bin/java -jar $SNAPCRAFT_PRIME/../apps/jython-installer.jar -v -s -d $SNAPCRAFT_PRIME/gluu-opt/jython -t standard -e ensurepip
      fi

  opendj:
    plugin: dump
    source: apps/opendj-server.zip
    source-type: zip
    organize:
      '*' : gluu-opt/
    stage-packages:
       - libpam-cap
       - libcap2-bin
    override-prime: |
      snapcraftctl prime
      echo "/var/snap/gluu-server/common/opendj" > $SNAPCRAFT_PRIME/gluu-opt/opendj/instance.loc

  oxauth:
    after: [jetty]
    plugin: nil
    override-prime: |
      snapcraftctl prime
      mkdir -p $SNAPCRAFT_PRIME/gluu-opt/dist/gluu
      mkdir -p $SNAPCRAFT_PRIME/gluu-opt/dist/scripts
      cp $SNAPCRAFT_PRIME/../apps/oxauth-server.war $SNAPCRAFT_PRIME/gluu-opt/dist/gluu/oxauth.war
      cp $SNAPCRAFT_PRIME/gluu-opt/jetty/bin/jetty.sh $SNAPCRAFT_PRIME/gluu-opt/dist/scripts/oxauth
    stage-packages:
      - dpkg
      - coreutils
      - login

  identity:
    plugin: nil
    after: [oxauth]
    override-prime: |
      snapcraftctl prime
      cp $SNAPCRAFT_PRIME/../apps/oxtrust-server.war $SNAPCRAFT_PRIME/gluu-opt/dist/gluu/identity.war
      cp $SNAPCRAFT_PRIME/gluu-opt/jetty/bin/jetty.sh $SNAPCRAFT_PRIME/gluu-opt/dist/scripts/identity

apps:

  bash:
    plugs:
     - network
     - network-bind
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA_BIN: "/opt/jre/bin/java"
      OPENDJ_JAVA_HOME: "/opt/jre"
    command: bin/bash

  python:
    plugs:
     - network
     - network-bind
    command: usr/bin/python3

  setup:
    plugs:
     - network
     - network-bind
    command: usr/bin/python3 $SNAP/bin/setup.py

  apache:
    command: usr/sbin/apachectl start
    #stop-command: usr/sbin/apachectl stop
    #daemon: forking
    #restart-condition: always
    plugs:
      - network
      - network-bind

  jython:
    environment:
      JAVA_HOME: "/opt/jre"
    command: gluu-opt/jre/bin/java  -jar $SNAP/gluu-opt/jython/jython.jar


  opendj-setup:
    plugs:
     - network
     - network-bind
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA_BIN: "/opt/jre/bin/java"
      OPENDJ_JAVA_HOME: "/opt/jre"
    command: gluu-opt/opendj/setup


  opendj:
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA_BIN: "/opt/jre/bin/java"
      OPENDJ_JAVA_HOME: "/opt/jre"
    plugs:
     - network
     - network-bind
    daemon: forking
    command: gluu-opt/opendj/bin/start-ds
    stop-command: gluu-opt/opendj/bin/stop-ds


  oxauth:
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA: "/opt/jre/bin/java"
      JETTY_HOME: "/opt/jetty"
      JETTY_RUN: "/tmp/jetty_temp"

    plugs:
     - network
     - network-bind

    daemon: forking
    command: gluu-opt/dist/scripts/oxauth start
    stop-command: gluu-opt/dist/scripts/oxauth stop


  identity:
    environment:
      JAVA_HOME: "/opt/jre"
      JAVA: "/opt/jre/bin/java"
      JETTY_HOME: "/opt/jetty"
      JETTY_RUN: "/tmp/jetty_temp"

    plugs:
     - network
     - network-bind

    daemon: forking
    command: gluu-opt/dist/scripts/identity start
    stop-command: gluu-opt/dist/scripts/identity stop
