#!/usr/bin/python3

import os
import zipfile
import shutil

snap_dir = os.environ['SNAP']
snap_common_dir = os.environ['SNAP_COMMON']

#Extract community edition setup

setup_package = os.path.join(snap_dir, 'gluu-opt/dist/gluu/community-edition-setup.zip')
target_base = os.path.join(snap_common_dir, 'install')
target_dir = os.path.join(target_base, 'community_edition_setup')

ces_zip = zipfile.ZipFile(setup_package)
ces_base_dir = ces_zip.namelist()[0]
ces_zip.extractall(target_base)

if not os.path.exists(target_base):
    os.mkdir(target_base)

if os.path.exists(target_dir):
    shutil.rmtree(target_dir)

extract_dir = os.path.join(target_base, ces_base_dir)

shutil.copytree(extract_dir, target_dir)

shutil.rmtree(extract_dir)

os.system("snapctl stop --disable gluu-server.opendj")
os.system('snapctl stop --disable gluu-server.oxauth')
os.system('mkdir -p $SNAP_COMMON/etc/gluu')
os.system('mkdir -p $SNAP_COMMON/run/jetty')



os.system('mkdir -p $SNAP_COMMON/etc/certs/')
os.system('mkdir -p $SNAP_COMMON/etc/default')
os.system('touch $SNAP_COMMON/etc/default/oxauth')


os.system('cp $SNAP/gluu-opt/jre/jre/lib/security/cacerts.bak $SNAP_COMMON/etc/certs/java-cacerts')
os.system('mkdir -p $SNAP_COMMON/gluu/jetty/oxauth/')
os.system('touch $SNAP_COMMON/gluu/jetty/oxauth/oxauth.state')
